### ISSUE TITLE
Make the cheat.sh provider URL configurable

### ISSUE THREAD

**Issue by anas-elgarhy** [orhun/halp#57]
The current implementation uses a static URL to fetch the sheet page from [cheat.sh](https://cheat.sh)  which works but, [cheat.sh](https://cheat.sh) is open source 💙 which means that any one can host an instance of it, and by natural if this someone use `halp` it likely that he/she wants from `halp` to use his instance, not the public one.

**The solution**
make the cheat.sh provider URL configurable with the configuration file or by the command line arguments or both

**Additional context**
The same thing applies to #56

**Comment by orhun** [comment]
Pretty good idea. We should definitely support such thing! Would you be down to implement it?

**Comment by anas-elgarhy** [comment]
It would be my pleasure
