### ISSUE TITLE
no help  flag doesn't work when I have set the `check_help` value to true in the config file

### ISSUE THREAD

**Issue by anas-elgarhy** [orhun/halp#63]
**Describe the bug**
The `--no-help` option doesn't do anything  when I use it

**To reproduce**
1. Run with `--no-help` argument
2. The program checks for the help info

**Expected behavior**
Halp doesn't should to check for the help info when I use the `--no-help` argument

**Screenshots / Logs**
![image](https://github.com/orhun/halp/assets/44965145/43152785-b19a-43a1-85e2-f8615032e381)

**Software information**
- Operating system: Arch GNU/Linux legion 6.3.8-zen1-1-zen  ZEN SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:15 +0000 x86_64
- Rust version: rustc 1.72.0-nightly (dd5d7c729 2023-06-02)
- Project version: halp 0.1.7

**Comment by orhun** [comment]
I cannot reproduce this.

```sh
$ halp halp --no-help
(°ロ°)  checking 'halp -v'
(×﹏×)      fail '-v' argument not found.
(°ロ°)  checking 'halp -V'
\(^ヮ^)/ success '-V' argument found!
---
halp 0.1.7
---
```

**Comment by anas-elgarhy** [comment]
__duplicated__: this is relatively the same issue as #64
