### ISSUE TITLE
Gets stuck in case of "pre-pagerized" help pages 

### ISSUE THREAD

**Issue by seqizz** [orhun/halp#9]
**Describe the bug**

Some apps might try to show their help pages with a pager already. Might want to pipe it to "cat" or call it in a way that the app doesn't think it's an interactive terminal.

**To reproduce**

1. Find a weird app (nix)
2. Call halp for it

**Expected behavior**

Seeing help page

**Screenshots / Logs**
```
~> ~/Downloads/halp-0.1.2/halp nix
(°ロ°)  checking 'nix -v'
(×﹏×)      fail '-v' argument not found.
(°ロ°)  checking 'nix -V'
(×﹏×)      fail '-V' argument not found.
(°ロ°)  checking 'nix --version'
\(^ヮ^)/ success '--version' argument found!
nix (Nix) 2.11.1
(°ロ°)  checking 'nix -h'
(×﹏×)      fail '-h' argument not found.
(°ロ°)  checking 'nix --help'
... stuck here :)
^C
Session terminated, killing shell...
```
**Software information**

- Operating system: NixOS 22.11
- Rust version: (not relevant I assume, this is prebuilt version from releases page)
- Project version: 0.1.2

**Additional context**

Thanks for the app, looks like a nice candidate as a life saver.

**Comment by orhun** [comment]
Thanks for reporting this! It is now fixed in 0917065daba3be58c829e2a276c17c31fdde23af

![rec_20230316T042119](https://user-images.githubusercontent.com/24392180/225485222-04821fcc-d527-4576-a79b-45d6c7c1bcdc.gif)

I will cut a new release shortly. 🐻
